### ISSUE TITLE
Yolov2 using Darknet

### ISSUE THREAD

**Issue by sharadhigm** [apoorvavinod/Real_time_Object_detection_and_tracking#12]
Does Darknet use TensorFlow to build the convolution layers?
Can u share any material on KCF tracker and its working implementation?
Thanks in advance!!

**Comment by apoorvavinod** [comment]
I am not sure about Darkflow since I have never used it. Yes, from what I gathered from searching on google; you can use Darknet weights for Darkflow.

**Comment by apoorvavinod** [comment]
It depends on the way you've converted the weights. From my experience, I've previously loaded the weights with retval = cv.dnn.readNetFromTensorflow( .pb, .pbtxt)
you have the .pb file already. Try here https://stackoverflow.com/questions/38549153/how-to-convert-protobuf-graph-to-binary-wire-format to generate the .pbtxt

**Comment by sharadhigm** [comment]
i was able to generate .pbtxt but endedup with the following error Failed to parse GraphDef file: model_data/yolov2.pbtxt in function 'ReadTFNetParamsFromBinaryFileOrDie'.Using Darkflow seperately i could run the Object detection.How do i merge it with the KCF tracker?

**Comment by apoorvavinod** [comment]
The tracker objects from opencv just need the output of your initial detection i.e  initialize the tracker with the bounding boxes that you get from the detection in darkflow and then call the tracker's `update` function to get new co-ordinates of the detected object. As for the .pbtxt file I am not sure what the issue is there.

**Comment by giorgiomondauto** [comment]
Any updates on how to generate a pbtxt file from .pb???
