### ISSUE TITLE
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""

### ISSUE THREAD

**Issue by N0ODle** [apoorvavinod/Real_time_Object_detection_and_tracking#21]
I am also facing an issue:

```
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Abort trap: 6
```

**Comment by quicktwit** [comment]
> I am also facing an issue:
> 
> ```
> qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Abort trap: 6
> ```
Check this link. I fixed it by 
`pip3 install python-opencv-headless`
`pip3 uninstall opencv-contrib-python`
Please refer this [link](https://stackoverflow.com/questions/60042568/this-application-failed-to-start-because-no-qt-platform-plugin-could-be-initiali) and this [link](https://github.com/ageitgey/face_recognition/issues/1041)
